# -*- coding: utf-8 -*-
"""power bi logistic regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14i-pIB3rZcmwB2Z_XXiOjF1Mo1-JKVRx
"""

# model 1

# basic libraries

import pandas as pd
import numpy as np

# load data set
data = pd.read_csv("digital_marketing_campaign_dataset_2.csv")
x = data[["Age", "Income_in_USD", "AdSpend_in_USD", "ConversionRate", "TimeOnSite_in_minutes", "PreviousPurchases" ]]
y = data.iloc[:, -1].values

# split data set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.4, random_state = 0)

# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# train model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

# testing
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

# metric
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score

# load data
data = pd.read_csv("C:\\Users\\dell\\Downloads\\sem 2 internship\\digital_marketing_campaign_dataset_2.csv")

# feature selection
x = data[["Age", "Income_in_USD", "AdSpend_in_USD", "ConversionRate", "TimeOnSite_in_minutes", "PreviousPurchases"]]
y = data.iloc[:, -1].values

# train-test split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=0)

# feature Scaling
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# Model training
classifier = LogisticRegression(random_state=0)
classifier.fit(x_train, y_train)

# Prediction
y_pred = classifier.predict(x_test)

# Evaluation of model
cm = confusion_matrix(y_test, y_pred)
cm_table = pd.DataFrame(cm, columns=['Predicted Negative', 'Predicted Positive'], index=['Actual Negative', 'Actual Positive'])
accuracy = accuracy_score(y_test, y_pred)

# Convert results to DataFrame
result_table = pd.DataFrame({
    'Actual': y_test,
    'Predicted': y_pred
})

# add new column
result_table['Accuracy'] = accuracy